manifest:

  self:
    path: jerry_z_tests
  
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: moduhub
      url-base: https://bitbucket.org/moduhub
 
  projects:
  
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.1.0
      import: true
  
    - name: hal_atmel
      remote: zephyrproject-rtos
      repo-path: hal_atmel
      path: modules/hal/atmel

    - name: zephyr_jerryscript
      url: https://github.com/moduhub/zephyr_jerryscript
      revision: master
      path: modules/lib/jerryscript
